
services:
  pdf-summary-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_api_key_here}
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - DEBUG=false
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    restart: unless-stopped
